### ISSUE TITLE
MM fails to discover/populate ASG, using weird endpoint for AWS API

### ISSUE THREAD

**Issue by anapsix** [argoproj/k8s-minion-manager#4]
Minion-Manager seems to be using a peculiar endpoint when talking to AWS Autoscaling API.
I've got the following setup:
- K8s cluster: `dev.rnd.pw`
- K8s nodes ASG: `nodes.dev.rnd.pw`
- Route 53 Zone Record: `*.dev.rnd.pw`
  - `api.dev.rnd.pw -> CNAME -> K8s API ELB`
  - `*.dev.rnd.pw -> CNAME -> Ingress ELB`
  - other records, not relevant to this issue
- `Ingress ELB` with `rnd.pw` SSL Cert with additional alternative names: `*.rnd.pw`, `*.dev.rnd.pw`

When launching Minion-Manger, it seems to attempt to talk to something in `*.dev.rnd.pw`, according to the error message mentioning the certificate. I've no idea how it would resolve `autoscaling.us-east-2.amazonaws.com` via `*.dev.rnd.pw` wildcard CNAME record.

Using `shrinand/k8s-minion-manager:v0.2-dev`
```
$ kubectl logs -f minion-manager-695dd4596f-nl5wd
2018-07-25T10:20:04 INFO minion_manager MainThread: Starting minion-manager for cluster: dev.rnd.pw, in region us-east-2 for cloud provider aws
2018-07-25T10:20:05 INFO aws_minion_manager MainThread: Running AWS Minion Manager
Traceback (most recent call last):
  File "./minion_manager.py", line 61, in <module>
    run()
  File "./minion_manager.py", line 57, in run
    minion_manager.run()
  File "/cloud_provider/aws/aws_minion_manager.py", line 495, in run
    str(ex))
Exception: Failed to discover/populate current ASG info: hostname 'autoscaling.us-east-2.amazonaws.com' doesn't match either of 'rnd.pw', '*.rnd.pw', '*.dev.rnd.pw'
```

Or using `argoproj/minion-manager`
```
$ kubectl logs -f minion-manager-dep-575cb9d695-7vrhl
2018-07-25T10:30:05 INFO minion_manager MainThread: Starting ...
2018-07-25T10:30:05 INFO minion_manager MainThread: Using config from env: us-east-2
2018-07-25T10:30:05 INFO minion_manager MainThread: Using config from env: ['nodes.dev.rnd.pw']
2018-07-25T10:30:05 INFO minion_manager MainThread: Starting minion-manager for scaling groups: ['nodes.dev.rnd.pw'], in region us-east-2 for cloud provider aws
2018-07-25T10:30:05 INFO aws.minion-manager MainThread: Running AWS Minion Manager
Traceback (most recent call last):
  File "/ax/bin/minion_manager", line 89, in <module>
    run()
  File "/ax/bin/minion_manager", line 79, in run
    minion_manager.run()
  File "/ax/python/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py", line 550, in run
    self.start()
  File "/ax/python/ax/platform/minion_manager/cloud_provider/aws/aws_minion_manager.py", line 152, in start
    str(ex))
Exception: Failed to discover/populate current ASG info: hostname 'autoscaling.us-east-2.amazonaws.com' doesn't match either of 'rnd.pw', '*.rnd.pw', '*.dev.rnd.pw'
```
As soon as I delete `*.dev.rnd.pw` DNS record, the problem disappears, and Minion-Manager discovers ASG just fine.

**Comment by shrinandj** [comment]
This particular repo (https://github.com/argoproj/k8s-minion-manager) should only be used with the `shrinand/k8s-minion-manager` docker image (Filed https://github.com/argoproj/k8s-minion-manager/issues/5 to move it under `argoproj`).

Minion-manager uses the boto3 python library for communicating with AWS. In the discovery phase, the minion-manager queries AWS to find ASGs with the appropriate tags. Looks like the hostname `autoscaling.us-east-2.amazonaws.com` does not get resolved causing the discovery phase to fail.

I've seen this problem in the past of [gossip based clusters](https://dzone.com/articles/creating-a-gossip-based-kubernetes-cluster-on-aws). To fix it, we explicitly had to change the `kube-dns` config-map (create one if it did not exist) and add an option in there to make the domain `amazonaws.com` resolve to `169.254.169.253` so that the DNS resolution of `amazonaws.com` happened at the ec2 instance.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      "internal": ["169.254.169.253"],
      "amazonaws.com": ["169.254.169.253"]
    }
```

In the case above, the cluster is not a gossip based cluster. @anapsix, you might also need to add the `amazonaws.com` domain to route53.

**Comment by anapsix** [comment]
wow, thanks for the tip @shrinandj, I'll give it a try.. 
btw, I've seen this behavior with both `shrinand/k8s-minion-manager:v0.2-dev` and `argoproj/minion-manager`, which is I've opened the issue here
Perhaps, this caveat could be added to Troubleshooting section, as it's not something obvious, imho.

**Comment by shrinandj** [comment]
Thanks! The problem seems to be unrelated to the minion-manager itself and more to do with the way DNS resolution is setup on the K8S cluster.

We have a "What happens when" section in the README. Similarly, we could add a "Troubleshooting" section in the Q&A format in the README itself. Do you want to create a Pull Request with that?

**Comment by anapsix** [comment]
Will do, when I verify the solution.. Wouldn't want to mislead :)
